previewsEnabled: false
previewsExpireAfterDays: 1

services:
  # App
  - type: web
    name: prod:app
    env: static
    rootDir: app/
    buildFilter:
      paths:
      - app/**
    buildCommand: ./scripts/render/build.sh
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # API
  - type: web
    name: prod:api
    env: python
    plan: starter
    rootDir: api/
    buildFilter:
      paths:
      - api/**
    startCommand: ./scripts/render/start.sh
    buildCommand: ./scripts/render/build.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.9
      - key: DATABASE_URL
        fromDatabase:
          name: prod:db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: prod:db
    databaseName: fiary
    user: admin
    plan: free
