# Generated by Django 4.1.2 on 2022-10-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notebook",
            name="title",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
