# Generated by Django 4.1.2 on 2022-11-03 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="page",
            old_name="color",
            new_name="bg_color",
        ),
    ]
