# Generated by Django 4.1.2 on 2022-11-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_color_page_bg_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="pattern_style",
            field=models.IntegerField(
                choices=[
                    (1, "Solid"),
                    (2, "Dots"),
                    (3, "Squares"),
                    (4, "Lines"),
                    (5, "Isometric"),
                ],
                default=1,
            ),
        ),
    ]
