# Generated by Django 4.1.2 on 2022-11-06 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_page_pattern_style"),
    ]

    operations = [
        migrations.RenameField(
            model_name="page",
            old_name="bg_color",
            new_name="paper_color",
        ),
        migrations.RenameField(
            model_name="page",
            old_name="pattern_style",
            new_name="pattern_type",
        ),
    ]
