# Generated by Django 4.1.2 on 2022-11-06 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0005_palette_paletteswatch_palettecollection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="palettecollection",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="palette_collection",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
