# Generated by Django 4.1.2 on 2022-11-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_palettecollection_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="paper_color",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="pattern_color",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
