# Generated by Django 4.1.2 on 2022-11-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_page_paper_color_alter_page_pattern_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="pattern_opacity",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="page",
            name="paper_color",
            field=models.JSONField(default="{r: 255, b: 255, g: 255, a: 1}"),
            preserve_default=False,
        ),
    ]
