# Generated by Django 4.1.2 on 2022-11-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_page_pattern_opacity_alter_page_paper_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="pattern_opacity",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
