# Generated by Django 4.1.2 on 2022-11-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_palette_collection_page_paper_swatch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paletteswatch",
            name="default_for",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Paper"), (10, "Pattern"), (20, "General")],
                default=None,
                null=True,
            ),
        ),
    ]
