# Generated by Django 4.1.2 on 2022-11-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_paletteswatch_default_for"),
    ]

    operations = [
        migrations.AlterField(
            model_name="palette",
            name="palette_type",
            field=models.IntegerField(
                choices=[(1, "Paper"), (10, "Pattern"), (20, "Tool")], default=20
            ),
        ),
        migrations.AlterField(
            model_name="paletteswatch",
            name="default_for",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Paper"), (10, "Pattern"), (20, "Tool")],
                default=None,
                null=True,
            ),
        ),
    ]
