# Generated by Django 4.1.2 on 2022-11-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_palette_palette_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paletteswatch",
            name="default_for",
        ),
        migrations.AddField(
            model_name="paletteswatch",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
