# Generated by Django 4.1.2 on 2022-11-08 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_paletteswatch_default_for_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="paper_color",
        ),
        migrations.RemoveField(
            model_name="page",
            name="pattern_color",
        ),
    ]
