# Generated by Django 4.1.2 on 2022-11-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_remove_page_paper_color_remove_page_pattern_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="palette",
            name="palette_type",
            field=models.IntegerField(
                choices=[
                    (1, "General"),
                    (10, "Paper"),
                    (20, "Pattern"),
                    (31, "Tool - Fill"),
                    (32, "Tool - Stroke"),
                ],
                default=1,
            ),
        ),
    ]
