# Generated by Django 4.1.2 on 2022-11-08 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_palette_palette_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paletteswatch",
            name="swatch_type",
        ),
    ]
