# Generated by Django 4.1.2 on 2022-11-11 23:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_remove_paletteswatch_swatch_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paletteswatch",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveField(
            model_name="element",
            name="fill_color",
        ),
        migrations.RemoveField(
            model_name="element",
            name="is_ruler_line",
        ),
        migrations.RemoveField(
            model_name="element",
            name="points",
        ),
        migrations.RemoveField(
            model_name="element",
            name="size",
        ),
        migrations.RemoveField(
            model_name="element",
            name="stroke_color",
        ),
        migrations.AddField(
            model_name="element",
            name="render",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="page",
            name="element_order",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="element",
            name="tool",
            field=models.IntegerField(
                choices=[
                    (1, "Eraser"),
                    (2, "Clear All"),
                    (10, "Pen"),
                    (11, "Marker"),
                    (12, "Highlighter"),
                    (20, "Blob"),
                    (30, "Circle"),
                    (31, "Rectangle"),
                    (32, "Triangle"),
                    (33, "Line"),
                    (40, "Cut"),
                    (41, "Paste"),
                    (50, "Image"),
                    (60, "Checkbox"),
                    (61, "Textbox"),
                    (70, "Paper"),
                ]
            ),
        ),
    ]
