# Generated by Django 4.1.2 on 2022-11-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_rename_id_bookshelf_uid_rename_id_element_uid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="element",
            old_name="render",
            new_name="renderRect",
        ),
        migrations.AddField(
            model_name="element",
            name="renderImage",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
