# Generated by Django 4.1.2 on 2022-11-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_rename_render_element_renderrect_element_renderimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="element",
            old_name="renderImage",
            new_name="image_render",
        ),
        migrations.RenameField(
            model_name="element",
            old_name="options",
            new_name="settings",
        ),
        migrations.RemoveField(
            model_name="element",
            name="renderRect",
        ),
        migrations.AddField(
            model_name="element",
            name="canvas_settings",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="element",
            name="dimensions",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="element",
            name="is_cached",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="element",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="element",
            name="is_html_element",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="element",
            name="points",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="element",
            name="transform",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
