# Generated by Django 4.1.2 on 2022-11-14 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_rename_renderimage_element_image_render_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="element",
            old_name="image_render",
            new_name="canvas_data_url",
        ),
    ]
