# Generated by Django 4.1.2 on 2022-12-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_rename_image_render_element_canvas_data_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="element",
            name="tool",
            field=models.IntegerField(
                choices=[
                    (10, "Eraser"),
                    (12, "Clear All"),
                    (20, "Pen"),
                    (21, "Marker"),
                    (22, "Highlighter"),
                    (30, "Blob"),
                    (40, "Circle"),
                    (41, "Rectangle"),
                    (42, "Triangle"),
                    (43, "Line"),
                    (50, "Cut"),
                    (51, "Paste"),
                    (60, "Image"),
                    (70, "Checkbox"),
                    (81, "Textbox"),
                ]
            ),
        ),
    ]
