# Generated by Django 4.1.4 on 2022-12-21 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_page_canvas_data_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="pattern_opacity",
        ),
        migrations.RemoveField(
            model_name="page",
            name="pattern_size",
        ),
        migrations.RemoveField(
            model_name="page",
            name="pattern_spacing",
        ),
        migrations.AddField(
            model_name="page",
            name="fill_swatch",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fill_swatch",
                to="core.paletteswatch",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="is_add_image_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="page",
            name="is_debug_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="page",
            name="is_interactive_edit_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="page",
            name="is_paste_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="page",
            name="is_ruler_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="page",
            name="is_textbox_edit_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="page",
            name="pattern_options",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="selected_line_end_side",
            field=models.IntegerField(
                choices=[(0, "None"), (1, "One"), (2, "Both")], default=0
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="selected_line_end_style",
            field=models.IntegerField(
                choices=[(0, "None"), (1, "Arrow"), (2, "Circle"), (3, "Square")],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="selected_tool",
            field=models.IntegerField(
                choices=[
                    (10, "Eraser"),
                    (12, "Clear All"),
                    (20, "Pen"),
                    (21, "Marker"),
                    (22, "Highlighter"),
                    (30, "Blob"),
                    (40, "Circle"),
                    (41, "Rectangle"),
                    (42, "Triangle"),
                    (43, "Line"),
                    (50, "Cut"),
                    (51, "Paste"),
                    (60, "Image"),
                    (70, "Checkbox"),
                    (81, "Textbox"),
                ],
                default=20,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="selected_tool_size",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="page",
            name="stroke_swatch",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stroke_swatch",
                to="core.paletteswatch",
            ),
        ),
    ]
