# Generated by Django 4.1.4 on 2023-01-06 05:13

from django.db import migrations
from core.choices import PaletteTypes


def setup_palettes(apps, schema_editor):
    Palette = apps.get_model("core", "Palette")
    PaletteSwatch = apps.get_model("core", "PaletteSwatch")
    User = apps.get_model("users", "User")

    superadmin = User.objects.get(username="superadmin")
    default_pattern_palette = Palette.objects.create(
        title="Default Pattern Palette",
        owner=superadmin,
        is_public=True,
        palette_type=PaletteTypes.PATTERN,
    )
    default_pattern_palette.save()

    default_paper_palette = Palette.objects.create(
        title="Default Paper Palette",
        owner=superadmin,
        is_public=True,
        palette_type=PaletteTypes.PAPER,
    )
    default_paper_palette.save()

    default_tool_fill_palette = Palette.objects.create(
        title="Default Tool (Fill) Palette",
        owner=superadmin,
        is_public=True,
        palette_type=PaletteTypes.TOOL_FILL,
    )
    default_tool_fill_palette.save()

    default_tool_stroke_palette = Palette.objects.create(
        title="Default Tool (Stroke) Palette",
        owner=superadmin,
        is_public=True,
        palette_type=PaletteTypes.TOOL_STROKE,
    )
    default_tool_stroke_palette.save()

    paper_swatches = [
        {"a": 1, "b": 255, "g": 255, "r": 255},
        {"a": 1, "b": 0, "g": 0, "r": 0},
        {"a": 1, "b": 232, "g": 250, "r": 255},
        {"a": 1, "b": 127, "g": 127, "r": 127},
    ]
    default_paper_swatch_idx = 0
    for idx, swatch in enumerate(paper_swatches):
        swatch = PaletteSwatch.objects.create(
            owner=superadmin,
            palette=default_paper_palette,
            swatch=swatch,
            is_default=idx == default_paper_swatch_idx,
        )
        swatch.save()

    pattern_swatches = [
        {"a": 1, "b": 255, "g": 255, "r": 255},
        {"a": 1, "b": 0, "g": 0, "r": 0},
        {"a": 1, "b": 232, "g": 250, "r": 255},
        {"a": 1, "b": 127, "g": 127, "r": 127},
    ]
    default_pattern_swatch_idx = 3
    for idx, swatch in enumerate(pattern_swatches):
        swatch = PaletteSwatch.objects.create(
            owner=superadmin,
            palette=default_pattern_palette,
            swatch=swatch,
            is_default=idx == default_pattern_swatch_idx,
        )
        swatch.save()


    tool_fill_swatches = [
        {"a": 0, "b": 0, "g": 0, "r": 0},
        {"a": 1, "b": 0, "g": 0, "r": 0},
    ]
    default_tool_fill_swatch_idx = 1
    for idx, swatch in enumerate(tool_fill_swatches):
        swatch = PaletteSwatch.objects.create(
            owner=superadmin,
            palette=default_tool_fill_palette,
            swatch=swatch,
            is_default=idx == default_tool_fill_swatch_idx,
        )
        swatch.save()

    tool_stroke_swatches = [
        {"a": 0, "b": 0, "g": 0, "r": 0},
        {"a": 1, "b": 0, "g": 0, "r": 0},
    ]
    default_tool_stroke_swatch_idx = 0
    for idx, swatch in enumerate(tool_stroke_swatches):
        swatch = PaletteSwatch.objects.create(
            owner=superadmin,
            palette=default_tool_stroke_palette,
            swatch=swatch,
            is_default=idx == default_tool_stroke_swatch_idx,
        )
        swatch.save()

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_remove_page_pattern_opacity_remove_page_pattern_size_and_more"),
    ]

    operations = [
        migrations.RunPython(setup_palettes),
    ]
